apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sample-company
  description: A collection of sample company
spec:
  targets:
    - ./all-apis.yaml
    - ./all-components.yaml
    - ./all-domains.yaml
    - ./all-resources.yaml
    - ./all-systems.yaml
