apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-a
  description: Sample Service A
  tags:
    - java
    - quarkus
spec:
  type: service
  lifecycle: production
  owner: group:sample-squad-a
  system: sample-system
  dependsOn:
  - resource:sample-kafka