apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-rest-api-a
  namespace: sample-namespace
  description: sample descriptions
  tags:
    - rest-api
    - backend
    - service
    - java
    - quarkus
spec:
  type: openapi
  lifecycle: production
  owner: group:sample-squad-a
  system: sample-system